
/*
====================
       CASO 1
====================
*/
-- A CONTINUACION EJECUTAR COMO ADMINISTRADOR / ADMIN (Oracle Cloud)

-- Creacion de roles
CREATE ROLE PRY2205_ROL_D; -- Asignado a usuario PRY2205_EFT_DES (Desarrollador)
CREATE ROLE PRY2205_ROL_C; -- Asignado a PRY2205_EFT_CON (Consultor)

-- Aisgnacion de permisos

GRANT CREATE SESSION TO PRY2205_ROL_D;
GRANT CREATE TABLE TO PRY2205_ROL_D;
GRANT CREATE VIEW TO PRY2205_ROL_D;
GRANT CREATE SYNONYM TO PRY2205_ROL_D;
GRANT CREATE PUBLIC SYNONYM TO PRY2205_ROL_D;
GRANT CREATE SEQUENCE TO PRY2205_ROL_D;
GRANT CREATE PROCEDURE TO PRY2205_ROL_D;
GRANT CREATE ANY INDEX TO PRY2205_ROL_D;

GRANT CREATE SESSION TO PRY2205_ROL_C;
GRANT CREATE SYNONYM TO PRY2205_ROL_C;
GRANT CREATE PUBLIC SYNONYM TO PRY2205_ROL_C;


-- Creacion de usuario

CREATE USER PRY2205_EFT 
IDENTIFIED BY "P2T5J6R:c(1P" 
DEFAULT TABLESPACE DATA 
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON DATA;

CREATE USER PRY2205_EFT_DES 
IDENTIFIED BY "fM@W;E{459Fy"
DEFAULT TABLESPACE DATA 
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON DATA;

CREATE USER PRY2205_EFT_CON 
IDENTIFIED BY "(xWQF28?=a`4"
DEFAULT TABLESPACE DATA 
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON DATA;

-- asignacion de roles

GRANT PRY2205_ROL_D TO PRY2205_EFT_DES;
GRANT PRY2205_ROL_C TO PRY2205_EFT_CON;

-- permisos adicionales de administrador para caso 3

GRANT DWROLE TO PRY2205_EFT;
GRANT CREATE TABLE TO PRY2205_EFT;
GRANT CREATE VIEW TO PRY2205_EFT;
GRANT CREATE SEQUENCE TO PRY2205_EFT;
GRANT CREATE SYNONYM TO PRY2205_EFT;
GRANT CREATE PUBLIC SYNONYM TO PRY2205_EFT;
GRANT CREATE ANY INDEX TO PRY2205_EFT;

/*
=====================================
se pide usar el scrip para poblar tablas aqui
=====================================
*/
-- creacion de sinonimos
CREATE OR REPLACE PUBLIC SYNONYM SYN_COM FOR PRY2205_EFT.COMUNA;
CREATE OR REPLACE PUBLIC SYNONYM SYN_CUO_TAR FOR PRY2205_EFT.CUOTA_TARJETAS;
CREATE OR REPLACE PUBLIC SYNONYM SYN_DEU FOR PRY2205_EFT.DEUDOR;
CREATE OR REPLACE PUBLIC SYNONYM SYN_FOR_PAG FOR PRY2205_EFT.FORMA_PAGO;
CREATE OR REPLACE PUBLIC SYNONYM SYN_OCU FOR PRY2205_EFT.OCUPACION;
CREATE OR REPLACE PUBLIC SYNONYM SYN_PAG FOR PRY2205_EFT.PAGOS_DEUDA;
CREATE OR REPLACE PUBLIC SYNONYM SYN_AVA FOR PRY2205_EFT.PARAM_AVANCES;
CREATE OR REPLACE PUBLIC SYNONYM SYN_PES_VIP FOR PRY2205_EFT.PESOS_VIP;
CREATE OR REPLACE PUBLIC SYNONYM SYN_PRO FOR PRY2205_EFT.PROVINCIA;
CREATE OR REPLACE PUBLIC SYNONYM SYN_REG FOR PRY2205_EFT.REGION;
CREATE OR REPLACE PUBLIC SYNONYM SYN_RES_AVA FOR PRY2205_EFT.RESUM_AVANCES_MES;
CREATE OR REPLACE PUBLIC SYNONYM SYN_SUC FOR PRY2205_EFT.SUCURSAL;
CREATE OR REPLACE PUBLIC SYNONYM SYN_ANAL_TAR FOR PRY2205_EFT.T_ANALISIS_TARJETAS;
CREATE OR REPLACE PUBLIC SYNONYM SYN_TAR_DEU FOR PRY2205_EFT.TARJETA_DEUDOR;
CREATE OR REPLACE PUBLIC SYNONYM SYN_TIP_TRAN_TAR FOR PRY2205_EFT.TIPO_TRANSACCION_TARJETA;
CREATE OR REPLACE PUBLIC SYNONYM SYN_TIP_DEU FOR PRY2205_EFT.TIPOS_DE_DEUDOR;
CREATE OR REPLACE PUBLIC SYNONYM SYN_TRAN_TAR_DEU FOR PRY2205_EFT.TRANSACCION_TARJETA_DEUDOR;

-- permisos de lectura solo para rol_c

GRANT SELECT ON PRY2205_EFT.COMUNA TO PRY2205_ROL_C;
GRANT SELECT ON PRY2205_EFT.CUOTA_TARJETAS TO PRY2205_ROL_C;
GRANT SELECT ON PRY2205_EFT.DEUDOR TO PRY2205_ROL_C;
GRANT SELECT ON PRY2205_EFT.FORMA_PAGO TO PRY2205_ROL_C;
GRANT SELECT ON PRY2205_EFT.OCUPACION TO PRY2205_ROL_C;
GRANT SELECT ON PRY2205_EFT.PAGOS_DEUDA TO PRY2205_ROL_C;
GRANT SELECT ON PRY2205_EFT.PARAM_AVANCES TO PRY2205_ROL_C;
GRANT SELECT ON PRY2205_EFT.PESOS_VIP TO PRY2205_ROL_C;
GRANT SELECT ON PRY2205_EFT.PROVINCIA TO PRY2205_ROL_C;
GRANT SELECT ON PRY2205_EFT.REGION TO PRY2205_ROL_C;
GRANT SELECT ON PRY2205_EFT.RESUM_AVANCES_MES TO PRY2205_ROL_C;
GRANT SELECT ON PRY2205_EFT.SUCURSAL TO PRY2205_ROL_C;
GRANT SELECT ON PRY2205_EFT.T_ANALISIS_TARJETAS TO PRY2205_ROL_C;
GRANT SELECT ON PRY2205_EFT.TARJETA_DEUDOR TO PRY2205_ROL_C;
GRANT SELECT ON PRY2205_EFT.TIPO_TRANSACCION_TARJETA TO PRY2205_ROL_C;
GRANT SELECT ON PRY2205_EFT.TIPOS_DE_DEUDOR TO PRY2205_ROL_C;
GRANT SELECT ON PRY2205_EFT.TRANSACCION_TARJETA_DEUDOR TO PRY2205_ROL_C;

-- Permisos completos para Rol_D
GRANT SELECT, INSERT, UPDATE, DELETE ON PRY2205_EFT.COMUNA TO PRY2205_ROL_D;
GRANT SELECT, INSERT, UPDATE, DELETE ON PRY2205_EFT.CUOTA_TARJETAS TO PRY2205_ROL_D;
GRANT SELECT, INSERT, UPDATE, DELETE ON PRY2205_EFT.DEUDOR TO PRY2205_ROL_D;
GRANT SELECT, INSERT, UPDATE, DELETE ON PRY2205_EFT.FORMA_PAGO TO PRY2205_ROL_D;
GRANT SELECT, INSERT, UPDATE, DELETE ON PRY2205_EFT.OCUPACION TO PRY2205_ROL_D;
GRANT SELECT, INSERT, UPDATE, DELETE ON PRY2205_EFT.PAGOS_DEUDA TO PRY2205_ROL_D;
GRANT SELECT, INSERT, UPDATE, DELETE ON PRY2205_EFT.PARAM_AVANCES TO PRY2205_ROL_D;
GRANT SELECT, INSERT, UPDATE, DELETE ON PRY2205_EFT.PESOS_VIP TO PRY2205_ROL_D;
GRANT SELECT, INSERT, UPDATE, DELETE ON PRY2205_EFT.PROVINCIA TO PRY2205_ROL_D;
GRANT SELECT, INSERT, UPDATE, DELETE ON PRY2205_EFT.REGION TO PRY2205_ROL_D;
GRANT SELECT, INSERT, UPDATE, DELETE ON PRY2205_EFT.RESUM_AVANCES_MES TO PRY2205_ROL_D;
GRANT SELECT, INSERT, UPDATE, DELETE ON PRY2205_EFT.SUCURSAL TO PRY2205_ROL_D;
GRANT SELECT, INSERT, UPDATE, DELETE ON PRY2205_EFT.T_ANALISIS_TARJETAS TO PRY2205_ROL_D;
GRANT SELECT, INSERT, UPDATE, DELETE ON PRY2205_EFT.TARJETA_DEUDOR TO PRY2205_ROL_D;
GRANT SELECT, INSERT, UPDATE, DELETE ON PRY2205_EFT.TIPO_TRANSACCION_TARJETA TO PRY2205_ROL_D;
GRANT SELECT, INSERT, UPDATE, DELETE ON PRY2205_EFT.TIPOS_DE_DEUDOR TO PRY2205_ROL_D;
GRANT SELECT, INSERT, UPDATE, DELETE ON PRY2205_EFT.TRANSACCION_TARJETA_DEUDOR TO PRY2205_ROL_D;

-- PERMISOS ESPECIALES PARA CASO 2 (Solución a ORA-01720)
-- Se otorgan directamente al usuario DES porque WITH GRANT OPTION no funciona en Roles

GRANT SELECT ON PRY2205_EFT.DEUDOR TO PRY2205_EFT_DES WITH GRANT OPTION;
GRANT SELECT ON PRY2205_EFT.OCUPACION TO PRY2205_EFT_DES WITH GRANT OPTION;
GRANT SELECT ON PRY2205_EFT.TARJETA_DEUDOR TO PRY2205_EFT_DES WITH GRANT OPTION;
GRANT SELECT ON PRY2205_EFT.CUOTA_TARJETAS TO PRY2205_EFT_DES WITH GRANT OPTION;

-- También para la tabla del Caso 3.1 para evitar el error de privilegios insuficientes
GRANT ALL ON PRY2205_EFT.T_ANALISIS_TARJETAS TO PRY2205_EFT_DES WITH GRANT OPTION;



/*
===================================
              CASO 2
!! EJECUTAR COMO PRY2205_EFT_DES !!
===================================
*/

-- creacion de vista
CREATE OR REPLACE VIEW VW_ANALISIS_DEUDORES_PERIODO AS
SELECT 

     TO_CHAR(SYN_DEU.NUMRUN, 'FM99G999G999', 'NLS_NUMERIC_CHARACTERS = '',.''') || '-' || SYN_DEU.DVRUN AS RUT_DEUDOR
,    INITCAP(SYN_DEU.PNOMBRE || ' ' || SYN_DEU.APPATERNO || ' ' || SYN_DEU.APMATERNO) AS "NOMBRE DEUDOR"
,    COUNT(SYN_CUO_TAR.NRO_CUOTA) AS TOTAL_CUOTAS
,    LPAD(TO_CHAR(ROUND(AVG(SYN_CUO_TAR.VALOR_CUOTA)), 'FM9999999999'), 15, ' ') AS PROMEDIO_VALOR_CUOTAS
,    NVL(TO_CHAR(SYN_DEU.FONO_CONTACTO), 'Sin Información') AS "TELEFONO"
,    TO_CHAR(MIN(SYN_CUO_TAR.FECHA_VENC_CUOTA), 'DD-MM-YYYY') AS "FECHA_MAS_ANTIGUA" -- Texto e imagen tenia discrepancias asi que me guio por la figura 2
,    RPAD(UPPER(SYN_OCU.NOMBRE_PROF_OFIC), 20, ' ')AS "OCUPACION"
,    LPAD(TO_CHAR(SYN_TAR_DEU.CUPO_DISP_COMPRA, 'FM9999999999'), 15, ' ') AS CUPO_DISP_COMPRA


    FROM 
        SYN_DEU 
    JOIN 
        SYN_OCU ON SYN_DEU.COD_OCUPACION = SYN_OCU.COD_OCUPACION
    JOIN 
        SYN_TAR_DEU ON SYN_DEU.NUMRUN = SYN_TAR_DEU.NUMRUN
    JOIN 
        SYN_CUO_TAR ON SYN_TAR_DEU.NRO_TARJETA = SYN_CUO_TAR.NRO_TARJETA
        
    WHERE -- Filtros
        UPPER(SYN_OCU.NOMBRE_PROF_OFIC) NOT LIKE '%INGENIERO%' -- excluye ingenieros
        AND EXTRACT(YEAR FROM SYN_CUO_TAR.FECHA_VENC_CUOTA) = EXTRACT(YEAR FROM SYSDATE) - 1 -- "la fecha de la cuota más vencida correspondiente al año anterior"
    
    GROUP BY -- Agrupacion necesaria para las columnas
        SYN_DEU.NUMRUN, 
        SYN_DEU.DVRUN, 
        SYN_DEU.PNOMBRE, 
        SYN_DEU.APPATERNO, 
        SYN_DEU.APMATERNO, 
        SYN_DEU.FONO_CONTACTO,
        SYN_TAR_DEU.CUPO_DISP_COMPRA,
        SYN_OCU.NOMBRE_PROF_OFIC 
    
    HAVING -- Condicion post agrupado "promedio de valor de cuotas es inferior al máximo de todos los promedios de cuotas de las tarjetas de crédito en general"
        AVG(SYN_CUO_TAR.VALOR_CUOTA) < (
            SELECT MAX(promedio_general)
            FROM (
                SELECT AVG(VALOR_CUOTA) as promedio_general
                FROM SYN_CUO_TAR
                GROUP BY NRO_TARJETA
            )
        )
    ORDER BY -- Para ordenar de cantidad de cuotas ascendente y luego por cupo disponible
        TOTAL_CUOTAS ASC, 
        SYN_TAR_DEU.CUPO_DISP_COMPRA ASC;

-- Verificación de las vistas
SELECT * FROM VW_ANALISIS_DEUDORES_PERIODO;

-- Asignacion de privilegios para el usuario consultor
GRANT SELECT ON VW_ANALISIS_DEUDORES_PERIODO TO PRY2205_EFT_CON;


/*
===================================
              CASO 3
!! EJECUTAR COMO PRY2205_EFT_DES !!
===================================
*/ 
-- para comenzar de 0

DROP SEQUENCE SEQ_T_ANALISIS;
DELETE FROM SYN_ANAL_TAR;

-- Creacion de la sequencia con el identificador correlativo NUM_ANALISIS
CREATE SEQUENCE SEQ_T_ANALISIS
    START WITH 1
    INCREMENT BY 1;

-- Sentencia DML para cargar datos en la tabla existente
INSERT INTO SYN_ANAL_TAR (
    NUM_ANALISIS
,   NRO_TARJETA
,   TOTAL_CUOTAS
,   MONTO_TOTAL_TRANSA
,   FECHA_TRANSACCION
,   DIRECCION
,   MONTO_REAJUSTADO
)
-- Uso de secuencia .NEXTVAL se aplica sobre el conjunto de datos ya ordenado
SELECT
    SEQ_T_ANALISIS.NEXTVAL AS NUM_ANALISIS
,   SUBCONSULTA.NRO_TARJETA
,   SUBCONSULTA.TOTAL_CUOTAS
,   SUBCONSULTA.MONTO_TOTAL_TRANSA
,   SUBCONSULTA.FECHA_TRANSACCION
,   SUBCONSULTA.DIRECCION
,   SUBCONSULTA.MONTO_REAJUSTADO
    
FROM (
  -- Subconsulta para procesar filtros y el orden 
    SELECT
        SYN_TRAN_TAR_DEU.NRO_TARJETA AS NRO_TARJETA
,       SYN_TRAN_TAR_DEU.TOTAL_CUOTAS_TRANSACCION AS TOTAL_CUOTAS
,       SYN_TRAN_TAR_DEU. MONTO_TOTAL_TRANSACCION AS MONTO_TOTAL_TRANSA
,       TO_CHAR(SYN_TRAN_TAR_DEU.FECHA_TRANSACCION, 'DD/MM/YYYY') AS FECHA_TRANSACCION
,       INITCAP(SYN_SUC.DIRECCION) AS DIRECCION
,       
        CASE
            WHEN SYN_TRAN_TAR_DEU.MONTO_TOTAL_TRANSACCION BETWEEN 200000 AND 300000
            THEN ROUND(SYN_TRAN_TAR_DEU.MONTO_TOTAL_TRANSACCION * 1.05)
                    
            WHEN SYN_TRAN_TAR_DEU.MONTO_TOTAL_TRANSACCION BETWEEN 300001 AND 500000
                THEN ROUND(SYN_TRAN_TAR_DEU.MONTO_TOTAL_TRANSACCION * 1.07)
                    
            ELSE SYN_TRAN_TAR_DEU.MONTO_TOTAL_TRANSACCION * 1
            
        END AS MONTO_REAJUSTADO
    
        FROM SYN_TRAN_TAR_DEU
    
        JOIN SYN_SUC ON SYN_SUC.ID_SUCURSAL = SYN_TRAN_TAR_DEU.ID_SUCURSAL
    
        WHERE-- Filtro
            UPPER(SYN_SUC.DIRECCION) LIKE 'A%'
            AND SYN_TRAN_TAR_DEU.MONTO_TOTAL_TRANSACCION >= 200000
            
    -- Ordenamiento
        ORDER BY SYN_TRAN_TAR_DEU.NRO_TARJETA ASC, MONTO_REAJUSTADO DESC
) SUBCONSULTA;

-- Confirmacion de cambios 
COMMIT;

-- Verificacion final
SELECT * FROM SYN_ANAL_TAR ORDER BY NRO_TARJETA ASC, MONTO_REAJUSTADO DESC;

-- CREACION DE INDICES

-- Indice para optimizar el filtro de búsqueda por Dirección (LIKE 'A%') Esto evita que Oracle lea toda la tabla SUCURSAL.
CREATE INDEX IDX_SUC_DIRECCION_BUSQ ON PRY2205_EFT.SUCURSAL(DIRECCION);

-- Indice para optimizar el filtro de Montos (>= 200000) Mejora drásticamente el rendimiento de la subconsulta del Caso 3.1.
CREATE INDEX IDX_TRA_MONTO_BUSQ ON PRY2205_EFT.TRANSACCION_TARJETA_DEUDOR(MONTO_TOTAL_TRANSACCION);

-- Indice para optimizar el JOIN entre Transacciones y Sucursales Indexar las llaves foráneas (FK) es una regla de oro en optimización.
CREATE INDEX IDX_TRA_SUCURSAL_FK 
ON PRY2205_EFT.TRANSACCION_TARJETA_DEUDOR(ID_SUCURSAL);

-- Otorgar permiso al consultor para ver la tabla cargada, según la pauta.
GRANT SELECT ON SYN_ANAL_TAR TO PRY2205_EFT_CON;




