-- Caso 1
DROP TABLE RECAUDACION_BONOS_MEDICOS CASCADE CONSTRAINTS PURGE; -- Elimino la tabla para comenzar limpio

CREATE TABLE RECAUDACION_BONOS_MEDICOS AS

SELECT 
     TO_CHAR(medico.rut_med, 'FM09G999G999', 'NLS_NUMERIC_CHARACTERS = '',.''') || '-' || MEDICO.DV_RUN AS "RUT_MEDICO"
,    MEDICO.PNOMBRE || ' ' || MEDICO.APATERNO || ' ' || MEDICO.AMATERNO AS "NOMBRE MÉDICO"
,    TO_CHAR(SUM(BONO_CONSULTA.COSTO), '$99G999G999', 'NLS_NUMERIC_CHARACTERS = '',.''') AS "TOTAL_RECAUDADO"
,    INITCAP(UNIDAD_CONSULTA.NOMBRE) as "UNIDAD_MEDICA"

FROM MEDICO
JOIN BONO_CONSULTA ON MEDICO.rut_med = BONO_CONSULTA.rut_med  -- Llamo a la tabla Bono Consulta
JOIN UNIDAD_CONSULTA ON MEDICO.uni_id = UNIDAD_CONSULTA.uni_id  -- Llamo a la tabla Unidad consulta
WHERE MEDICO.CAR_ID NOT IN (100, 500, 600)   -- Filtro
GROUP BY 
    MEDICO.RUT_MED, 
    MEDICO.DV_RUN, 
    MEDICO.PNOMBRE, 
    MEDICO.APATERNO, 
    MEDICO.AMATERNO,
    UNIDAD_CONSULTA.NOMBRE;
    
SELECT * FROM RECAUDACION_BONOS_MEDICOS  -- Llamo a mi nueva tabla
ORDER BY TOTAL_RECAUDADO ASC; -- Orden ascendente

-- Caso 2

SELECT
    ESPECIALIDAD_MEDICA.NOMBRE AS "ESPECIALIDAD MEDICA"
,   COUNT(BONO_CONSULTA.ID_BONO) AS "CANTIDAD BONOS"
,   TO_CHAR(SUM(BONO_CONSULTA.COSTO), '$99G999G999', 'NLS_NUMERIC_CHARACTERS = '',.''') AS "MONTO PÉRDIDA"
,   TO_CHAR(MIN(BONO_CONSULTA.FECHA_BONO), 'DD-MM-YYYY') AS "FECHA BONO"
,   CASE   
        WHEN EXTRACT(YEAR FROM MIN(BONO_CONSULTA.FECHA_BONO)) >= EXTRACT(YEAR FROM SYSDATE) - 1 
        THEN 'COBRABLE'
        ELSE 'INCOBRABLE'
    END AS "ESTADO DE COBRO"

FROM BONO_CONSULTA
JOIN ESPECIALIDAD_MEDICA ON BONO_CONSULTA.ESP_ID = ESPECIALIDAD_MEDICA.ESP_ID
WHERE BONO_CONSULTA.ID_BONO IN (
    SELECT ID_BONO FROM BONO_CONSULTA
    MINUS
    SELECT ID_BONO FROM PAGOS )
GROUP BY ESPECIALIDAD_MEDICA.NOMBRE
ORDER BY "CANTIDAD BONOS" ASC, "MONTO PÉRDIDA" DESC;

-- Caso 3   


DELETE FROM CANT_BONOS_PACIENTES_ANNIO;  -- Borro datos erroneos para empezar bien
COMMIT;

INSERT INTO CANT_BONOS_PACIENTES_ANNIO (ANNIO_CALCULO, PAC_RUN, DV_RUN, EDAD, CANTIDAD_BONOS, MONTO_TOTAL_BONOS, SISTEMA_SALUD)

SELECT 
    EXTRACT(YEAR FROM SYSDATE) AS ANNIO_CALCULO,
    PACIENTE.PAC_RUN,
    PACIENTE.DV_RUN,
    TRUNC(MONTHS_BETWEEN(SYSDATE, PACIENTE.FECHA_NACIMIENTO) / 12) AS EDAD,
    COUNT(BONO_CONSULTA.ID_BONO) AS CANTIDAD_BONOS,
    NVL(SUM(BONO_CONSULTA.COSTO), 0) AS "MONTO_TOTAL_BONOS",
    
    CASE 
        WHEN SALUD.DESCRIPCION IN ('Tramo A', 'Tramo B', 'Tramo C', 'Tramo D')
            THEN 'FONASA'
        
        WHEN SALUD.DESCRIPCION IN ('Mas Vida', 'Colmena', 'Banmedica', 'Cruz Blanca', 'Consalud', 'Vida Tres')
            THEN 'PARTICULARES'
            
        WHEN SALUD.DESCRIPCION IN (
            'Personal activo FFAA',
            'Carga Familar Personal FFAA',
            'Personal Retirado FFAA',
            'Personal activo de carabienros y PDI',
            'Carga Familar Personal Carabineros y PDI',
            'Personal Retirado Carabineros y PDI'
        )
            THEN 'FUERZAS ARMADAS'
            ELSE 'OTRO/NO AFILIADO'
    END AS SISTEMA_SALUD

FROM PACIENTE

LEFT JOIN BONO_CONSULTA ON PACIENTE.PAC_RUN = BONO_CONSULTA.PAC_RUN 
                          AND EXTRACT(YEAR FROM BONO_CONSULTA.FECHA_BONO) = EXTRACT(YEAR FROM SYSDATE)
JOIN SALUD ON PACIENTE.SAL_ID = SALUD.SAL_ID

WHERE SALUD.DESCRIPCION <> 'Personal no afiliado a un sistema de salud'

GROUP BY 
    PACIENTE.PAC_RUN,
    PACIENTE.DV_RUN,
    PACIENTE.FECHA_NACIMIENTO,
    SALUD.DESCRIPCION
    
HAVING 
    NVL(COUNT(BONO_CONSULTA.ID_BONO), 0) <= (
        SELECT ROUND(AVG(COUNT(ID_BONO)))
        FROM BONO_CONSULTA
        WHERE EXTRACT(YEAR FROM FECHA_BONO) = EXTRACT(YEAR FROM SYSDATE) - 1
        GROUP BY PAC_RUN
    );

COMMIT;

SELECT * FROM CANT_BONOS_PACIENTES_ANNIO ORDER BY MONTO_TOTAL_BONOS ASC, EDAD DESC;

