-- Caso 1
-- Se comienza por crear el rol

CREATE ROLE PRY2205_ROL_D;
CREATE ROLE PRY2205_ROL_P;

-- Asignacion de permisos

GRANT CREATE TABLE TO PRY2205_ROL_D;
GRANT CREATE VIEW TO PRY2205_ROL_D;
GRANT CREATE ANY INDEX TO PRY2205_ROL_D;
GRANT CREATE SYNONYM TO PRY2205_ROL_D;
GRANT CREATE PUBLIC SYNONYM TO PRY2205_ROL_D;
GRANT CREATE SESSION TO PRY2205_ROL_D;

GRANT CREATE VIEW TO PRY2205_ROL_P;
GRANT CREATE PROFILE TO PRY2205_ROL_P;
GRANT CREATE USER TO PRY2205_ROL_P;

-- Se crean los usarios y se asignan los roles

CREATE USER PRY2205_USER1
IDENTIFIED BY "FF@pf(L3071S"
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON DATA;

CREATE USER PRY2205_USER2
IDENTIFIED BY "FF@pf(L3071S"
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON DATA;

GRANT PRY2205_ROL_D TO PRY2205_USER1;
GRANT PRY2205_ROL_P TO PRY2205_USER2;

--creacion de sinonimos para cada tabla

CREATE PUBLIC SYNONYM BONO_CON FOR PRY2205_USER1.BONO_CONSULTA;
CREATE PUBLIC SYNONYM BONO_PAC_ANNIO FOR PRY2205_USER1.CANT_BONOS_PACIENTES_ANNIO;
CREATE PUBLIC SYNONYM CARGO FOR PRY2205_USER1.CARGO;
CREATE PUBLIC SYNONYM DET_ESP_MED FOR PRY2205_USER1.DET_ESPECIALIDAD_MED;
CREATE PUBLIC SYNONYM ESP_MED FOR PRY2205_USER1.ESPECIALIDAD_MEDICA;
CREATE PUBLIC SYNONYM MEDICO FOR PRY2205_USER1.MEDICO;
CREATE PUBLIC SYNONYM PACIENTE FOR PRY2205_USER1.PACIENTE;
CREATE PUBLIC SYNONYM PAGOS FOR PRY2205_USER1.PAGOS;
CREATE PUBLIC SYNONYM DSCT_ADUL_MAY FOR PRY2205_USER1.PCT_DESCTO_ADULTO_MAYOR;
CREATE PUBLIC SYNONYM SALUD FOR PRY2205_USER1.SALUD;
CREATE PUBLIC SYNONYM SIS_SALUD FOR PRY2205_USER1.SISTEMA_SALUD;
CREATE PUBLIC SYNONYM CONSULTA FOR PRY2205_USER1.UNIDAD_CONSULTA;

-- Select al segundo rol para las consultas

GRANT SELECT ON PRY2205_USER1.BONO_CONSULTA TO PRY2205_ROL_P;
GRANT SELECT ON PRY2205_USER1.CANT_BONOS_PACIENTES_ANNIO TO PRY2205_ROL_P;
GRANT SELECT ON PRY2205_USER1.CARGO TO PRY2205_ROL_P;
GRANT SELECT ON PRY2205_USER1.DET_ESPECIALIDAD_MED TO PRY2205_ROL_P;
GRANT SELECT ON PRY2205_USER1.ESPECIALIDAD_MEDICA TO PRY2205_ROL_P;
GRANT SELECT ON PRY2205_USER1.MEDICO TO PRY2205_ROL_P;
GRANT SELECT ON PRY2205_USER1.PACIENTE TO PRY2205_ROL_P;
GRANT SELECT ON PRY2205_USER1.PAGOS TO PRY2205_ROL_P;
GRANT SELECT ON PRY2205_USER1.PCT_DESCTO_ADULTO_MAYOR TO PRY2205_ROL_P;
GRANT SELECT ON PRY2205_USER1.SALUD TO PRY2205_ROL_P;
GRANT SELECT ON PRY2205_USER1.SISTEMA_SALUD TO PRY2205_ROL_P;
GRANT SELECT ON PRY2205_USER1.UNIDAD_CONSULTA TO PRY2205_ROL_P;

-- Caso 2

CREATE OR REPLACE VIEW VW_RECALCULO_COSTOS AS
SELECT
    TO_CHAR(PACIENTE.PAC_RUN, 'FM99G999G999', 'NLS_NUMERIC_CHARACTERS = '',.''') || '-' || PACIENTE.DV_RUN AS RUT_PACIENTE
    ,UPPER(PACIENTE.PNOMBRE || ' ' || PACIENTE.APATERNO || ' ' || PACIENTE.AMATERNO) AS NOMBRE_PACIENTE
    ,SALUD.DESCRIPCION SISTEMA_SALUD
    ,TO_CHAR(BONO_CON.COSTO, '$99G999G999', 'NLS_NUMERIC_CHARACTERS = '',.''') AS COSTO
    ,BONO_CON.HR_CONSULTA AS HORARIO_ATENCION
    ,TO_CHAR(BONO_CON.FECHA_BONO, 'MM-YYYY') AS FECHA_BONO
    ,TO_CHAR(CASE 
        WHEN BONO_CON.COSTO BETWEEN 15000 AND 25000 THEN ROUND(BONO_CON.COSTO * 1.15)
        WHEN BONO_CON.COSTO > 25000 THEN ROUND(BONO_CON.COSTO * 1.20)
        ELSE BONO_CON.COSTO
    END, '$99G999G999', 'NLS_NUMERIC_CHARACTERS = '',.''') AS "REAJUSTE"
    FROM PACIENTE
    
    JOIN SALUD
        ON PACIENTE.SAL_ID = SALUD.SAL_ID
        
    JOIN BONO_CON
        ON PACIENTE.PAC_RUN = BONO_CON.PAC_RUN
        
    WHERE 
        BONO_CON.HR_CONSULTA > '17:15'
        AND EXTRACT(YEAR FROM BONO_CON.FECHA_BONO) = EXTRACT(YEAR FROM SYSDATE) - 1
        AND (SALUD.SAL_ID BETWEEN 10 AND 100)
        
    ORDER BY
        BONO_CON.FECHA_BONO ASC,
        PACIENTE.PAC_RUN ASC; -- cuenta de todas maneras los dias en la fecha bono
        
-- Caso 3

CREATE OR REPLACE VIEW VW_AUM_MEDICO_X_CARGO AS
SELECT 
    MEDICO.RUT_MED || '-' || MEDICO.DV_RUN AS RUT_MEDICO,
    CARGO.NOMBRE AS "CARGO",
    TO_CHAR(MEDICO.SUELDO_BASE, '$99G999G999', 'NLS_NUMERIC_CHARACTERS = '',.''') AS SUELDO_ACTUAL,
    TO_CHAR(ROUND(MEDICO.SUELDO_BASE * 1.15), '99G999G999', 'NLS_NUMERIC_CHARACTERS = '',.''') AS SUELDO_AUMENTADO
        FROM MEDICO
        
    JOIN CARGO 
        ON MEDICO.CAR_ID = CARGO.CAR_ID
        
    ORDER BY ROUND(MEDICO.SUELDO_BASE * 1.15) DESC;

-- creacion del Index 

CREATE INDEX IDX_MEDICO_CAR_ID 
    ON MEDICO(CAR_ID);


